In [2]:

import pandas as pd

In [3]:
# Wikipedia URL
url = "https://en.wikipedia.org/wiki/Forbes_list_of_the_world%27s_highest-paid_athletes"

# Extract all tables from the page
tables = pd.read_html(url)
tables

[   Rank                   Name                 Sport        Country  \
 0     1      Cristiano Ronaldo  Association football       Portugal
 1     2               Jon Rahm                  Golf          Spain
 2     3           Lionel Messi  Association football      Argentina
 3     4           LeBron James            Basketball  United States
 4     5  Giannis Antetokounmpo            Basketball         Greece
 5     6          Kylian Mbappé  Association football         France
 6     7                 Neymar  Association football         Brazil
 7     8          Karim Benzema  Association football         France
 8     9          Stephen Curry            Basketball  United States
 9    10          Lamar Jackson     American football  United States

             Total Salary/winnings Endorsements
 0    $260 million    $200 million  $60 million
 1    $218 million    $198 million  $20 million
 2    $135 million     $65 million  $70 million
 3  $128.2 million   $48.2 million  $80 million
 4    $111 million     $46 million  $65 million
 5    $110 million     $90 million  $20 million
 6    $108 million     $80 million  $28 million
 7    $106 million    $100 million   $6 million
 8    $102 million     $52 million  $50 million
 9  $100.5 million   $98.5 million   $2 million  ,
    Rank               Name                 Sport        Country  \
 0     1  Cristiano Ronaldo  Association football       Portugal
 1     2       Lionel Messi  Association football      Argentina
 2     3      Kylian Mbappé  Association football         France
 3     4       LeBron James            Basketball  United States
 4     5     Canelo Álvarez                Boxing         Mexico
 5     6     Dustin Johnson                  Golf  United States
 6     7     Phil Mickelson                  Golf  United States
 7     8      Stephen Curry            Basketball  United States
 8     9      Roger Federer                Tennis    Switzerland
 9    10       Kevin Durant            Basketball  United States

             Total Salary/winnings Endorsements
 0    $136 million     $46 million  $90 million
 1    $130 million     $65 million  $65 million
 2    $120 million    $100 million  $20 million
 3  $119.5 million   $44.5 million  $75 million
 4    $110 million    $100 million  $10 million
 5    $107 million    $102 million   $5 million
 6    $106 million    $104 million   $2 million
 7  $100.4 million   $48.4 million  $52 million
 8   $95.1 million    $0.1 million  $95 million
 9   $89.1 million   $44.1 million  $45 million  ,
    Rank                   Name                 Sport        Country  \
 0     1           Lionel Messi  Association football      Argentina
 1     2           LeBron James            Basketball  United States
 2     3      Cristiano Ronaldo  Association football       Portugal
 3     4                 Neymar  Association football         Brazil
 4     5          Stephen Curry            Basketball  United States
 5     6           Kevin Durant            Basketball  United States
 6     7          Roger Federer                Tennis    Switzerland
 7     8         Canelo Álvarez                Boxing         Mexico
 8     9              Tom Brady     American football  United States
 9    10  Giannis Antetokounmpo            Basketball         Greece

             Total Salary/winnings Endorsements
 0    $130 million     $75 million  $55 million
 1  $121.2 million   $41.2 million  $80 million
 2    $115 million     $60 million  $55 million
 3     $95 million     $70 million  $25 million
 4   $92.8 million   $45.8 million  $47 million
 5   $92.1 million   $42.1 million  $50 million
 6   $90.7 million    $0.7 million  $90 million
 7     $90 million     $85 million   $5 million
 8   $83.9 million   $31.9 million  $52 million
 9   $80.9 million   $39.9 million  $41 million  ,
    Rank               Name                 Sport              Country  \
 0     1     Conor McGregor    Mixed martial arts  Republic of Ireland
 1     2       Lionel Messi  Association football            Argentina
 2     3  Cristiano Ronaldo  Association football             Portugal
 3     4       Dak Prescott     American football        United States
 4     5       LeBron James            Basketball        United States
 5     6             Neymar  Association football               Brazil
 6     7      Roger Federer                Tennis          Switzerland
 7     8     Lewis Hamilton           Auto racing       United Kingdom
 8     9          Tom Brady     American football        United States
 9    10       Kevin Durant            Basketball        United States

             Total Salary/winnings  Endorsements
 0    $180 million     $22 million  $158 million
 1    $130 million     $97 million   $33 million
 2    $120 million     $70 million   $50 million
 3  $107.5 million   $97.5 million   $10 million
 4   $96.5 million   $31.5 million   $65 million
 5     $95 million     $76 million   $19 million
 6     $90 million   $0.03 million   $90 million
 7     $82 million     $70 million   $12 million
 8     $76 million     $45 million   $31 million
 9     $75 million     $31 million   $44 million  ,
    Rank               Name                 Sport        Country  \
 0     1      Roger Federer                Tennis    Switzerland
 1     2  Cristiano Ronaldo  Association football       Portugal
 2     3       Lionel Messi  Association football      Argentina
 3     4             Neymar  Association football         Brazil
 4     5       LeBron James            Basketball  United States
 5     6      Stephen Curry            Basketball  United States
 6     7       Kevin Durant            Basketball  United States
 7     8        Tiger Woods                  Golf  United States
 8     9       Kirk Cousins     American football  United States
 9    10       Carson Wentz     American football  United States

             Total Salary/winnings  Endorsements
 0  $106.3 million    $6.3 million  $100 million
 1    $105 million     $60 million   $45 million
 2    $104 million     $72 million   $32 million
 3   $95.5 million   $70.5 million   $25 million
 4   $88.2 million   $28.2 million   $60 million
 5   $74.4 million   $30.4 million   $44 million
 6   $63.9 million   $28.9 million   $35 million
 7   $62.3 million    $2.3 million   $60 million
 8   $60.5 million     $58 million  $2.5 million
 9   $59.1 million   $55.1 million    $4 million  ,
    Rank                  Name                 Sport          Nation  \
 0     1  Floyd Mayweather Jr.                Boxing   United States
 1     2     Cristiano Ronaldo  Association football        Portugal
 2     3          Lionel Messi  Association football       Argentina
 3     4          LeBron James            Basketball   United States
 4     5         Roger Federer                Tennis     Switzerland
 5     6           Tiger Woods                  Golf   United States
 6     7        Phil Mickelson                  Golf   United States
 7     8        Manny Pacquiao                Boxing     Philippines
 8     9          Kevin Durant            Basketball   United States
 9    10        Lewis Hamilton           Auto racing  United Kingdom

        Earnings
 0  $915 million
 1  $800 million
 2  $750 million
 3  $680 million
 4  $640 million
 5  $615 million
 6  $480 million
 7  $435 million
 8  $425 million
 9  $400 million  ,
    Rank               Name                 Sport         Nation  \
 0     1       Lionel Messi  Association football      Argentina
 1     2  Cristiano Ronaldo  Association football       Portugal
 2     3             Neymar  Association football         Brazil
 3     4     Canelo Álvarez                Boxing         Mexico
 4     5      Roger Federer                Tennis    Switzerland
 5     6     Russell Wilson     American football  United States
 6     7      Aaron Rodgers     American football  United States
 7     8       LeBron James            Basketball  United States
 8     9      Stephen Curry            Basketball  United States
 9    10       Kevin Durant            Basketball  United States

            Total Salary/Winnings Endorsements
 0   $127 million     $92 million  $35 million
 1   $109 million     $65 million  $44 million
 2   $105 million     $75 million  $30 million
 3    $94 million     $92 million   $2 million
 4  $93.4 million    $7.4 million  $86 million
 5  $89.5 million   $80.5 million   $9 million
 6  $89.3 million   $80.3 million   $9 million
 7    $89 million     $36 million  $53 million
 8  $79.8 million   $37.8 million  $42 million
 9  $65.4 million   $30.4 million  $35 million  ,
    Rank                  Name                 Sport               Nation  \
 0     1  Floyd Mayweather Jr.                Boxing        United States
 1     2          Lionel Messi  Association football            Argentina
 2     3     Cristiano Ronaldo  Association football             Portugal
 3     4        Conor McGregor    Mixed martial arts  Republic of Ireland
 4     5                Neymar  Association football               Brazil
 5     6          LeBron James            Basketball        United States
 6     7         Roger Federer                Tennis          Switzerland
 7     8         Stephen Curry            Basketball        United States
 8     9             Matt Ryan     American football        United States
 9    10      Matthew Stafford     American football        United States

            Total Salary/Winnings Endorsements
 0   $285 million    $275 million  $10 million
 1   $111 million     $84 million  $27 million
 2   $108 million     $61 million  $47 million
 3    $99 million     $85 million  $14 million
 4    $90 million     $73 million  $17 million
 5  $85.5 million   $33.5 million  $52 million
 6  $77.2 million   $12.2 million  $65 million
 7  $76.9 million   $34.9 million  $42 million
 8  $67.3 million   $62.3 million   $5 million
 9  $59.5 million   $57.5 million   $2 million  ,
    Rank               Name                 Sport            Nation  \
 0     1  Cristiano Ronaldo  Association football          Portugal
 1     2       LeBron James            Basketball     United States
 2     3       Lionel Messi  Association football         Argentina
 3     4      Roger Federer                Tennis       Switzerland
 4     5       Kevin Durant            Basketball     United States
 5     6        Andrew Luck     American football     United States
 6     6       Rory McIlroy                  Golf  Northern Ireland
 7     8      Stephen Curry            Basketball     United States
 8     9       James Harden            Basketball     United States
 9    10     Lewis Hamilton           Auto racing    United Kingdom

            Total Salary/Winnings Endorsements
 0    $93 million     $58 million  $35 million
 1  $86.2 million   $31.2 million  $55 million
 2    $80 million     $53 million  $27 million
 3    $64 million      $6 million  $58 million
 4  $60.6 million   $26.6 million  $34 million
 5    $50 million     $47 million   $3 million
 6    $50 million     $16 million  $34 million
 7  $47.3 million   $12.3 million  $35 million
 8  $46.6 million   $26.6 million  $20 million
 9    $46 million     $38 million   $8 million  ,
    Rank               Name                 Sport         Nation  \
 0     1  Cristiano Ronaldo  Association football       Portugal
 1     2       Lionel Messi  Association football      Argentina
 2     3       LeBron James            Basketball  United States
 3     4      Roger Federer                Tennis    Switzerland
 4     5       Kevin Durant            Basketball  United States
 5     6     Novak Djokovic                Tennis         Serbia
 6     7         Cam Newton     American football  United States
 7     8     Phil Mickelson                  Golf  United States
 8     9      Jordan Spieth                  Golf  United States
 9    10        Kobe Bryant            Basketball  United States

            Total Salary/Winnings Endorsements
 0    $88 million     $56 million  $32 million
 1  $81.4 million   $53.4 million  $28 million
 2  $77.2 million   $23.2 million  $54 million
 3  $67.8 million    $7.8 million  $60 million
 4  $56.2 million   $20.2 million  $36 million
 5  $55.8 million   $21.8 million  $34 million
 6  $53.1 million   $41.1 million  $12 million
 7  $52.9 million    $2.9 million  $50 million
 8  $52.8 million   $20.8 million  $32 million
 9    $50 million     $25 million  $25 million  ,
    Rank                  Name                 Sport         Nation  \
 0     1  Floyd Mayweather Jr.                Boxing  United States
 1     2        Manny Pacquiao                Boxing    Philippines
 2     3     Cristiano Ronaldo  Association football       Portugal
 3     4          Lionel Messi  Association football      Argentina
 4     5         Roger Federer                Tennis    Switzerland
 5     6          LeBron James            Basketball  United States
 6     7          Kevin Durant            Basketball  United States
 7     8        Phil Mickelson                  Golf  United States
 8     9           Tiger Woods                  Golf  United States
 9    10           Kobe Bryant            Basketball  United States

            Total Salary/Winnings Endorsements
 0   $300 million    $285 million  $15 million
 1   $160 million    $148 million  $12 million
 2  $79.6 million   $52.6 million  $27 million
 3  $73.8 million   $51.8 million  $22 million
 4    $67 million      $9 million  $58 million
 5  $64.8 million   $20.8 million  $44 million
 6  $54.1 million   $19.1 million  $35 million
 7  $50.8 million    $2.8 million  $48 million
 8  $50.6 million    $0.6 million  $50 million
 9  $49.5 million   $23.5 million  $26 million  ,
    Rank                  Name                 Sport         Nation  \
 0     1  Floyd Mayweather Jr.                Boxing  United States
 1     2     Cristiano Ronaldo  Association football       Portugal
 2     3          LeBron James            Basketball  United States
 3     4          Lionel Messi  Association football      Argentina
 4     5           Kobe Bryant            Basketball  United States
 5     6           Tiger Woods                  Golf  United States
 6     7         Roger Federer                Tennis    Switzerland
 7     8        Phil Mickelson                  Golf  United States
 8     9          Rafael Nadal                Tennis          Spain
 9    10             Matt Ryan     American football  United States

            Total Salary/Winnings  Endorsements
 0   $105 million    $105 million            $0
 1    $80 million     $52 million   $28 million
 2  $72.3 million   $19.3 million   $53 million
 3  $64.7 million   $41.7 million   $23 million
 4  $61.5 million   $30.5 million   $31 million
 5  $61.2 million    $6.2 million   $55 million
 6  $56.2 million    $4.2 million   $52 million
 7  $53.2 million    $5.2 million   $48 million
 8  $44.5 million   $14.5 million   $30 million
 9  $43.8 million     $42 million  $1.8 million  ,
    Rank               Name                 Sport          Nation  \
 0     1        Tiger Woods                  Golf   United States
 1     2      Roger Federer                Tennis     Switzerland
 2     3        Kobe Bryant            Basketball   United States
 3     4       LeBron James            Basketball   United States
 4     5         Drew Brees     American football   United States
 5     6      Aaron Rodgers     American football   United States
 6     7     Phil Mickelson                  Golf   United States
 7     8      David Beckham  Association football  United Kingdom
 8     9  Cristiano Ronaldo  Association football        Portugal
 9    10       Lionel Messi  Association football       Argentina

            Total Salary/Winnings Endorsements
 0  $78.1 million   $13.1 million  $65 million
 1  $71.5 million    $6.5 million  $65 million
 2  $61.9 million   $27.9 million  $34 million
 3  $59.8 million   $17.8 million  $42 million
 4    $51 million     $40 million  $11 million
 5    $49 million     $43 million   $6 million
 6  $48.7 million    $4.7 million  $44 million
 7  $47.2 million    $5.2 million  $42 million
 8    $44 million     $23 million  $21 million
 9  $41.3 million   $20.3 million  $21 million  ,
    Rank                  Name                 Sport     Nationality  \
 0     1  Floyd Mayweather Jr.                Boxing   United States
 1     2        Manny Pacquiao                Boxing     Philippines
 2     3           Tiger Woods                  Golf   United States
 3     4          LeBron James            Basketball   United States
 4     5         Roger Federer                Tennis     Switzerland
 5     6           Kobe Bryant            Basketball   United States
 6     7        Phil Mickelson                  Golf   United States
 7     8         David Beckham  Association football  United Kingdom
 8     9     Cristiano Ronaldo  Association football        Portugal
 9    10        Peyton Manning     American football   United States

   Total earnings Salary/winnings Endorsements
 0    $85 million     $85 million           $0
 1    $62 million     $56 million   $6 million
 2  $59.4 million    $4.4 million  $55 million
 3    $53 million     $13 million  $40 million
 4  $52.7 million    $7.7 million  $45 million
 5  $52.3 million   $20.3 million  $32 million
 6  $47.8 million    $4.8 million  $43 million
 7    $46 million      $9 million  $37 million
 8  $42.5 million   $20.5 million  $22 million
 9  $42.4 million   $32.4 million  $10 million  ,
    vteForbes magazine                               vteForbes magazine.1  \
 0           Companies                      Forbes Global 2000 Forbes 500
 1              People  The World's Billionaires Forbes 400 30 Under 3...
 2       Entertainment  General Forbes Top 40 Celebrity 100 Forbes Fic...
 3             General  Forbes Top 40 Celebrity 100 Forbes Fictional 1...
 4             Fashion                                Highest-paid models
 5                Film                                Highest-paid actors
 6               Music                             Highest-paid musicians
 7               Sport  Highest-paid athletes Most valuable sports tea...
 8           Education                             America's Top Colleges
 9          Technology                Midas List (Tech's Top Deal Makers)
 10     Related topics  Lists of people by net worth Wealthiest celebr...

     vteForbes magazine.2
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 5                    NaN
 6                    NaN
 7                    NaN
 8                    NaN
 9                    NaN
 10                   NaN  ,
          0                                                  1
 0  General  Forbes Top 40 Celebrity 100 Forbes Fictional 1...
 1  Fashion                                Highest-paid models
 2     Film                                Highest-paid actors
 3    Music                             Highest-paid musicians
 4    Sport  Highest-paid athletes Most valuable sports tea...]

In [4]:
years = list(range(2024, 2019, -1)) + list(range(2019, 2011, -1))
years

[2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]

In [20]:
tables_to_merge = tables[:5] + tables[6:14]
tables_to_merge

[   Rank                   Name                 Sport        Country  \
 0     1      Cristiano Ronaldo  Association football       Portugal
 1     2               Jon Rahm                  Golf          Spain
 2     3           Lionel Messi  Association football      Argentina
 3     4           LeBron James            Basketball  United States
 4     5  Giannis Antetokounmpo            Basketball         Greece
 5     6          Kylian Mbappé  Association football         France
 6     7                 Neymar  Association football         Brazil
 7     8          Karim Benzema  Association football         France
 8     9          Stephen Curry            Basketball  United States
 9    10          Lamar Jackson     American football  United States

             Total Salary/winnings Endorsements
 0    $260 million    $200 million  $60 million
 1    $218 million    $198 million  $20 million
 2    $135 million     $65 million  $70 million
 3  $128.2 million   $48.2 million  $80 million
 4    $111 million     $46 million  $65 million
 5    $110 million     $90 million  $20 million
 6    $108 million     $80 million  $28 million
 7    $106 million    $100 million   $6 million
 8    $102 million     $52 million  $50 million
 9  $100.5 million   $98.5 million   $2 million  ,
    Rank               Name                 Sport        Country  \
 0     1  Cristiano Ronaldo  Association football       Portugal
 1     2       Lionel Messi  Association football      Argentina
 2     3      Kylian Mbappé  Association football         France
 3     4       LeBron James            Basketball  United States
 4     5     Canelo Álvarez                Boxing         Mexico
 5     6     Dustin Johnson                  Golf  United States
 6     7     Phil Mickelson                  Golf  United States
 7     8      Stephen Curry            Basketball  United States
 8     9      Roger Federer                Tennis    Switzerland
 9    10       Kevin Durant            Basketball  United States

             Total Salary/winnings Endorsements
 0    $136 million     $46 million  $90 million
 1    $130 million     $65 million  $65 million
 2    $120 million    $100 million  $20 million
 3  $119.5 million   $44.5 million  $75 million
 4    $110 million    $100 million  $10 million
 5    $107 million    $102 million   $5 million
 6    $106 million    $104 million   $2 million
 7  $100.4 million   $48.4 million  $52 million
 8   $95.1 million    $0.1 million  $95 million
 9   $89.1 million   $44.1 million  $45 million  ,
    Rank                   Name                 Sport        Country  \
 0     1           Lionel Messi  Association football      Argentina
 1     2           LeBron James            Basketball  United States
 2     3      Cristiano Ronaldo  Association football       Portugal
 3     4                 Neymar  Association football         Brazil
 4     5          Stephen Curry            Basketball  United States
 5     6           Kevin Durant            Basketball  United States
 6     7          Roger Federer                Tennis    Switzerland
 7     8         Canelo Álvarez                Boxing         Mexico
 8     9              Tom Brady     American football  United States
 9    10  Giannis Antetokounmpo            Basketball         Greece

             Total Salary/winnings Endorsements
 0    $130 million     $75 million  $55 million
 1  $121.2 million   $41.2 million  $80 million
 2    $115 million     $60 million  $55 million
 3     $95 million     $70 million  $25 million
 4   $92.8 million   $45.8 million  $47 million
 5   $92.1 million   $42.1 million  $50 million
 6   $90.7 million    $0.7 million  $90 million
 7     $90 million     $85 million   $5 million
 8   $83.9 million   $31.9 million  $52 million
 9   $80.9 million   $39.9 million  $41 million  ,
    Rank               Name                 Sport              Country  \
 0     1     Conor McGregor    Mixed martial arts  Republic of Ireland
 1     2       Lionel Messi  Association football            Argentina
 2     3  Cristiano Ronaldo  Association football             Portugal
 3     4       Dak Prescott     American football        United States
 4     5       LeBron James            Basketball        United States
 5     6             Neymar  Association football               Brazil
 6     7      Roger Federer                Tennis          Switzerland
 7     8     Lewis Hamilton           Auto racing       United Kingdom
 8     9          Tom Brady     American football        United States
 9    10       Kevin Durant            Basketball        United States

             Total Salary/winnings  Endorsements
 0    $180 million     $22 million  $158 million
 1    $130 million     $97 million   $33 million
 2    $120 million     $70 million   $50 million
 3  $107.5 million   $97.5 million   $10 million
 4   $96.5 million   $31.5 million   $65 million
 5     $95 million     $76 million   $19 million
 6     $90 million   $0.03 million   $90 million
 7     $82 million     $70 million   $12 million
 8     $76 million     $45 million   $31 million
 9     $75 million     $31 million   $44 million  ,
    Rank               Name                 Sport        Country  \
 0     1      Roger Federer                Tennis    Switzerland
 1     2  Cristiano Ronaldo  Association football       Portugal
 2     3       Lionel Messi  Association football      Argentina
 3     4             Neymar  Association football         Brazil
 4     5       LeBron James            Basketball  United States
 5     6      Stephen Curry            Basketball  United States
 6     7       Kevin Durant            Basketball  United States
 7     8        Tiger Woods                  Golf  United States
 8     9       Kirk Cousins     American football  United States
 9    10       Carson Wentz     American football  United States

             Total Salary/winnings  Endorsements
 0  $106.3 million    $6.3 million  $100 million
 1    $105 million     $60 million   $45 million
 2    $104 million     $72 million   $32 million
 3   $95.5 million   $70.5 million   $25 million
 4   $88.2 million   $28.2 million   $60 million
 5   $74.4 million   $30.4 million   $44 million
 6   $63.9 million   $28.9 million   $35 million
 7   $62.3 million    $2.3 million   $60 million
 8   $60.5 million     $58 million  $2.5 million
 9   $59.1 million   $55.1 million    $4 million  ,
    Rank               Name                 Sport         Nation  \
 0     1       Lionel Messi  Association football      Argentina
 1     2  Cristiano Ronaldo  Association football       Portugal
 2     3             Neymar  Association football         Brazil
 3     4     Canelo Álvarez                Boxing         Mexico
 4     5      Roger Federer                Tennis    Switzerland
 5     6     Russell Wilson     American football  United States
 6     7      Aaron Rodgers     American football  United States
 7     8       LeBron James            Basketball  United States
 8     9      Stephen Curry            Basketball  United States
 9    10       Kevin Durant            Basketball  United States

            Total Salary/Winnings Endorsements
 0   $127 million     $92 million  $35 million
 1   $109 million     $65 million  $44 million
 2   $105 million     $75 million  $30 million
 3    $94 million     $92 million   $2 million
 4  $93.4 million    $7.4 million  $86 million
 5  $89.5 million   $80.5 million   $9 million
 6  $89.3 million   $80.3 million   $9 million
 7    $89 million     $36 million  $53 million
 8  $79.8 million   $37.8 million  $42 million
 9  $65.4 million   $30.4 million  $35 million  ,
    Rank                  Name                 Sport               Nation  \
 0     1  Floyd Mayweather Jr.                Boxing        United States
 1     2          Lionel Messi  Association football            Argentina
 2     3     Cristiano Ronaldo  Association football             Portugal
 3     4        Conor McGregor    Mixed martial arts  Republic of Ireland
 4     5                Neymar  Association football               Brazil
 5     6          LeBron James            Basketball        United States
 6     7         Roger Federer                Tennis          Switzerland
 7     8         Stephen Curry            Basketball        United States
 8     9             Matt Ryan     American football        United States
 9    10      Matthew Stafford     American football        United States

            Total Salary/Winnings Endorsements
 0   $285 million    $275 million  $10 million
 1   $111 million     $84 million  $27 million
 2   $108 million     $61 million  $47 million
 3    $99 million     $85 million  $14 million
 4    $90 million     $73 million  $17 million
 5  $85.5 million   $33.5 million  $52 million
 6  $77.2 million   $12.2 million  $65 million
 7  $76.9 million   $34.9 million  $42 million
 8  $67.3 million   $62.3 million   $5 million
 9  $59.5 million   $57.5 million   $2 million  ,
    Rank               Name                 Sport            Nation  \
 0     1  Cristiano Ronaldo  Association football          Portugal
 1     2       LeBron James            Basketball     United States
 2     3       Lionel Messi  Association football         Argentina
 3     4      Roger Federer                Tennis       Switzerland
 4     5       Kevin Durant            Basketball     United States
 5     6        Andrew Luck     American football     United States
 6     6       Rory McIlroy                  Golf  Northern Ireland
 7     8      Stephen Curry            Basketball     United States
 8     9       James Harden            Basketball     United States
 9    10     Lewis Hamilton           Auto racing    United Kingdom

            Total Salary/Winnings Endorsements
 0    $93 million     $58 million  $35 million
 1  $86.2 million   $31.2 million  $55 million
 2    $80 million     $53 million  $27 million
 3    $64 million      $6 million  $58 million
 4  $60.6 million   $26.6 million  $34 million
 5    $50 million     $47 million   $3 million
 6    $50 million     $16 million  $34 million
 7  $47.3 million   $12.3 million  $35 million
 8  $46.6 million   $26.6 million  $20 million
 9    $46 million     $38 million   $8 million  ,
    Rank               Name                 Sport         Nation  \
 0     1  Cristiano Ronaldo  Association football       Portugal
 1     2       Lionel Messi  Association football      Argentina
 2     3       LeBron James            Basketball  United States
 3     4      Roger Federer                Tennis    Switzerland
 4     5       Kevin Durant            Basketball  United States
 5     6     Novak Djokovic                Tennis         Serbia
 6     7         Cam Newton     American football  United States
 7     8     Phil Mickelson                  Golf  United States
 8     9      Jordan Spieth                  Golf  United States
 9    10        Kobe Bryant            Basketball  United States

            Total Salary/Winnings Endorsements
 0    $88 million     $56 million  $32 million
 1  $81.4 million   $53.4 million  $28 million
 2  $77.2 million   $23.2 million  $54 million
 3  $67.8 million    $7.8 million  $60 million
 4  $56.2 million   $20.2 million  $36 million
 5  $55.8 million   $21.8 million  $34 million
 6  $53.1 million   $41.1 million  $12 million
 7  $52.9 million    $2.9 million  $50 million
 8  $52.8 million   $20.8 million  $32 million
 9    $50 million     $25 million  $25 million  ,
    Rank                  Name                 Sport         Nation  \
 0     1  Floyd Mayweather Jr.                Boxing  United States
 1     2        Manny Pacquiao                Boxing    Philippines
 2     3     Cristiano Ronaldo  Association football       Portugal
 3     4          Lionel Messi  Association football      Argentina
 4     5         Roger Federer                Tennis    Switzerland
 5     6          LeBron James            Basketball  United States
 6     7          Kevin Durant            Basketball  United States
 7     8        Phil Mickelson                  Golf  United States
 8     9           Tiger Woods                  Golf  United States
 9    10           Kobe Bryant            Basketball  United States

            Total Salary/Winnings Endorsements
 0   $300 million    $285 million  $15 million
 1   $160 million    $148 million  $12 million
 2  $79.6 million   $52.6 million  $27 million
 3  $73.8 million   $51.8 million  $22 million
 4    $67 million      $9 million  $58 million
 5  $64.8 million   $20.8 million  $44 million
 6  $54.1 million   $19.1 million  $35 million
 7  $50.8 million    $2.8 million  $48 million
 8  $50.6 million    $0.6 million  $50 million
 9  $49.5 million   $23.5 million  $26 million  ,
    Rank                  Name                 Sport         Nation  \
 0     1  Floyd Mayweather Jr.                Boxing  United States
 1     2     Cristiano Ronaldo  Association football       Portugal
 2     3          LeBron James            Basketball  United States
 3     4          Lionel Messi  Association football      Argentina
 4     5           Kobe Bryant            Basketball  United States
 5     6           Tiger Woods                  Golf  United States
 6     7         Roger Federer                Tennis    Switzerland
 7     8        Phil Mickelson                  Golf  United States
 8     9          Rafael Nadal                Tennis          Spain
 9    10             Matt Ryan     American football  United States

            Total Salary/Winnings  Endorsements
 0   $105 million    $105 million            $0
 1    $80 million     $52 million   $28 million
 2  $72.3 million   $19.3 million   $53 million
 3  $64.7 million   $41.7 million   $23 million
 4  $61.5 million   $30.5 million   $31 million
 5  $61.2 million    $6.2 million   $55 million
 6  $56.2 million    $4.2 million   $52 million
 7  $53.2 million    $5.2 million   $48 million
 8  $44.5 million   $14.5 million   $30 million
 9  $43.8 million     $42 million  $1.8 million  ,
    Rank               Name                 Sport          Nation  \
 0     1        Tiger Woods                  Golf   United States
 1     2      Roger Federer                Tennis     Switzerland
 2     3        Kobe Bryant            Basketball   United States
 3     4       LeBron James            Basketball   United States
 4     5         Drew Brees     American football   United States
 5     6      Aaron Rodgers     American football   United States
 6     7     Phil Mickelson                  Golf   United States
 7     8      David Beckham  Association football  United Kingdom
 8     9  Cristiano Ronaldo  Association football        Portugal
 9    10       Lionel Messi  Association football       Argentina

            Total Salary/Winnings Endorsements
 0  $78.1 million   $13.1 million  $65 million
 1  $71.5 million    $6.5 million  $65 million
 2  $61.9 million   $27.9 million  $34 million
 3  $59.8 million   $17.8 million  $42 million
 4    $51 million     $40 million  $11 million
 5    $49 million     $43 million   $6 million
 6  $48.7 million    $4.7 million  $44 million
 7  $47.2 million    $5.2 million  $42 million
 8    $44 million     $23 million  $21 million
 9  $41.3 million   $20.3 million  $21 million  ,
    Rank                  Name                 Sport     Nationality  \
 0     1  Floyd Mayweather Jr.                Boxing   United States
 1     2        Manny Pacquiao                Boxing     Philippines
 2     3           Tiger Woods                  Golf   United States
 3     4          LeBron James            Basketball   United States
 4     5         Roger Federer                Tennis     Switzerland
 5     6           Kobe Bryant            Basketball   United States
 6     7        Phil Mickelson                  Golf   United States
 7     8         David Beckham  Association football  United Kingdom
 8     9     Cristiano Ronaldo  Association football        Portugal
 9    10        Peyton Manning     American football   United States

   Total earnings Salary/winnings Endorsements
 0    $85 million     $85 million           $0
 1    $62 million     $56 million   $6 million
 2  $59.4 million    $4.4 million  $55 million
 3    $53 million     $13 million  $40 million
 4  $52.7 million    $7.7 million  $45 million
 5  $52.3 million   $20.3 million  $32 million
 6  $47.8 million    $4.8 million  $43 million
 7    $46 million      $9 million  $37 million
 8  $42.5 million   $20.5 million  $22 million
 9  $42.4 million   $32.4 million  $10 million  ]

In [25]:
if len(tables_to_merge) == len(years):
    for i, year in enumerate(years):
        tables_to_merge[i]['Year'] = year
    # Merge all tables into one DataFrame
    aths_df = pd.concat(tables_to_merge, join="outer", ignore_index=True)

    # Display the first few rows
    #print(merged_df.head())

else:
    print(f"Mismatch: Found {len(tables_to_merge)} tables but expected {len(years)}.")

In [26]:
aths_df

,Rank,Name,Sport,Country,Total,Salary/winnings,Endorsements,Year,Nation,Salary/Winnings,Nationality,Total earnings
0,1,Cristiano Ronaldo,Association football,Portugal,$260 million,$200 million,$60 million,2024,NaN,NaN,NaN,NaN
1,2,Jon Rahm,Golf,Spain,$218 million,$198 million,$20 million,2024,NaN,NaN,NaN,NaN
2,3,Lionel Messi,Association football,Argentina,$135 million,$65 million,$70 million,2024,NaN,NaN,NaN,NaN
3,4,LeBron James,Basketball,United States,$128.2 million,$48.2 million,$80 million,2024,NaN,NaN,NaN,NaN
4,5,Giannis Antetokounmpo,Basketball,Greece,$111 million,$46 million,$65 million,2024,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
125,6,Kobe Bryant,Basketball,NaN,NaN,$20.3 million,$32 million,2012,NaN,NaN,United States,$52.3 million
126,7,Phil Mickelson,Golf,NaN,NaN,$4.8 million,$43 million,2012,NaN,NaN,United States,$47.8 million
127,8,David Beckham,Association football,NaN,NaN,$9 million,$37 million,2012,NaN,NaN,United Kingdom,$46 million
128,9,Cristiano Ronaldo,Association football,NaN,NaN,$20.5 million,$22 million,2012,NaN,NaN,Portugal,$42.5 million
129,10,Peyton Manning,American football,NaN,NaN,$32.4 million,$10 million,2012,NaN,NaN,United States,$42.4 million

In [29]:
aths_df.shape()

In [31]:
aths_df.to_csv("C:\\Users\\HP\\highest_paid_aths.csv")

Empty DataFrame
Columns: [Rank, Name, Sport, Country, Total, Salary/winnings, Endorsements, Year, Nation, Salary/Winnings, Nationality, Total earnings]
Index: []